# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastdocumenso',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/fastdocumenso',
                'lib_path': 'fastdocumenso'},
  'syms': { 'fastdocumenso.core': { 'fastdocumenso.core._encode_form': ('core.html#_encode_form', 'fastdocumenso/core.py'),
                                    'fastdocumenso.core.documenso_client': ('core.html#documenso_client', 'fastdocumenso/core.py'),
                                    'fastdocumenso.core.update_spec': ('core.html#update_spec', 'fastdocumenso/core.py')},
            'fastdocumenso.skill': {}}}
