spec = {'base_url': 'https://app.documenso.com/api/v2',
 'ops': [{'group': 'envelope', 'name': 'envelope_attachment_find', 'path': '/envelope/attachment', 'verb': 'GET', 'summary': 'Find attachments', 'query_params': ['envelopeId', 'token'], 'required_params': ['envelopeId'], 'param_types': {'envelopeId': 'str', 'token': 'str'}},
         {'group': 'envelope', 'name': 'envelope_attachment_create', 'path': '/envelope/attachment/create', 'verb': 'POST', 'summary': 'Create attachment', 'body_params': ['envelopeId', 'data'], 'request_content_type': 'application/json', 'required_params': ['data', 'envelopeId'], 'param_types': {'envelopeId': 'str', 'data': 'dict'}},
         {'group': 'envelope', 'name': 'envelope_attachment_update', 'path': '/envelope/attachment/update', 'verb': 'POST', 'summary': 'Update attachment', 'body_params': ['id', 'data'], 'request_content_type': 'application/json', 'required_params': ['data', 'id'], 'param_types': {'id': 'str', 'data': 'dict'}},
         {'group': 'envelope', 'name': 'envelope_attachment_delete', 'path': '/envelope/attachment/delete', 'verb': 'POST', 'summary': 'Delete attachment', 'body_params': ['id'], 'request_content_type': 'application/json', 'required_params': ['id'], 'param_types': {'id': 'str'}},
         {'group': 'envelope', 'name': 'envelope_item_create_many', 'path': '/envelope/item/create-many', 'verb': 'POST', 'summary': 'Create envelope items', 'body_params': ['payload', 'files'], 'file_params': ['files'], 'request_content_type': 'multipart/form-data', 'required_params': ['payload'], 'param_types': {'payload': 'dict', 'files': 'list'}},
         {'group': 'envelope', 'name': 'envelope_item_update_many', 'path': '/envelope/item/update-many', 'verb': 'POST', 'summary': 'Update envelope items', 'body_params': ['envelopeId', 'data'], 'request_content_type': 'application/json', 'required_params': ['data', 'envelopeId'], 'param_types': {'envelopeId': 'str', 'data': 'list'}},
         {'group': 'envelope', 'name': 'envelope_item_delete', 'path': '/envelope/item/delete', 'verb': 'POST', 'summary': 'Delete envelope item', 'body_params': ['envelopeId', 'envelopeItemId'], 'request_content_type': 'application/json', 'required_params': ['envelopeId', 'envelopeItemId'], 'param_types': {'envelopeId': 'str', 'envelopeItemId': 'str'}},
         {'group': 'envelope',
          'name': 'envelope_item_download',
          'path': '/envelope/item/{envelopeItemId}/download',
          'verb': 'GET',
          'summary': 'Download an envelope item',
          'route_params': ['envelopeItemId'],
          'query_params': ['version'],
          'required_params': ['envelopeItemId'],
          'param_types': {'envelopeItemId': 'str', 'version': 'str'},
          'param_defaults': {'version': 'signed'},
          'param_docs': {'envelopeItemId': 'The ID of the envelope item to download.',
                         'version': 'The version of the envelope item to download. "signed" returns the completed document with all signatures and the audit trail, "original" returns the original uploaded document, "pending" returns the original document with currently-inserted fields burned in (only valid while the envelope is in PENDING status; not a '
                                    'final executed document).'}},
         {'group': 'envelope', 'name': 'envelope_recipient_get', 'path': '/envelope/recipient/{recipientId}', 'verb': 'GET', 'summary': 'Get envelope recipient', 'route_params': ['recipientId'], 'required_params': ['recipientId'], 'param_types': {'recipientId': 'float'}},
         {'group': 'envelope', 'name': 'envelope_recipient_create_many', 'path': '/envelope/recipient/create-many', 'verb': 'POST', 'summary': 'Create envelope recipients', 'body_params': ['envelopeId', 'data'], 'request_content_type': 'application/json', 'required_params': ['data', 'envelopeId'], 'param_types': {'envelopeId': 'str', 'data': 'list'}},
         {'group': 'envelope', 'name': 'envelope_recipient_update_many', 'path': '/envelope/recipient/update-many', 'verb': 'POST', 'summary': 'Update envelope recipients', 'body_params': ['envelopeId', 'data'], 'request_content_type': 'application/json', 'required_params': ['data', 'envelopeId'], 'param_types': {'envelopeId': 'str', 'data': 'list'}},
         {'group': 'envelope', 'name': 'envelope_recipient_delete', 'path': '/envelope/recipient/delete', 'verb': 'POST', 'summary': 'Delete envelope recipient', 'body_params': ['recipientId'], 'request_content_type': 'application/json', 'required_params': ['recipientId'], 'param_types': {'recipientId': 'float'}},
         {'group': 'envelope',
          'name': 'envelope_recipient_reject_on_behalf_of',
          'path': '/envelope/recipient/{recipientId}/reject',
          'verb': 'POST',
          'summary': 'Reject envelope recipient on behalf of',
          'route_params': ['recipientId'],
          'body_params': ['envelopeId', 'reason', 'actAsEmail'],
          'request_content_type': 'application/json',
          'required_params': ['envelopeId', 'reason', 'recipientId'],
          'param_types': {'recipientId': 'float', 'envelopeId': 'str', 'reason': 'str', 'actAsEmail': 'str'},
          'param_docs': {'recipientId': 'The ID of the recipient to reject the document on behalf of.'}},
         {'group': 'envelope', 'name': 'envelope_field_get', 'path': '/envelope/field/{fieldId}', 'verb': 'GET', 'summary': 'Get envelope field', 'route_params': ['fieldId'], 'required_params': ['fieldId'], 'param_types': {'fieldId': 'float'}},
         {'group': 'envelope', 'name': 'envelope_field_create_many', 'path': '/envelope/field/create-many', 'verb': 'POST', 'summary': 'Create envelope fields', 'body_params': ['envelopeId', 'data'], 'request_content_type': 'application/json', 'required_params': ['data', 'envelopeId'], 'param_types': {'envelopeId': 'str', 'data': 'list'}},
         {'group': 'envelope', 'name': 'envelope_field_update_many', 'path': '/envelope/field/update-many', 'verb': 'POST', 'summary': 'Update envelope fields', 'body_params': ['envelopeId', 'data'], 'request_content_type': 'application/json', 'required_params': ['data', 'envelopeId'], 'param_types': {'envelopeId': 'str', 'data': 'list'}},
         {'group': 'envelope', 'name': 'envelope_field_delete', 'path': '/envelope/field/delete', 'verb': 'POST', 'summary': 'Delete envelope field', 'body_params': ['fieldId'], 'request_content_type': 'application/json', 'required_params': ['fieldId'], 'param_types': {'fieldId': 'float'}},
         {'group': 'envelope',
          'name': 'envelope_find',
          'path': '/envelope',
          'verb': 'GET',
          'summary': 'Find envelopes',
          'query_params': ['query', 'page', 'perPage', 'type', 'templateId', 'source', 'status', 'hasExpiredRecipients', 'folderId', 'orderByColumn', 'orderByDirection'],
          'param_types': {'query': 'str', 'page': 'float', 'perPage': 'float', 'type': 'str', 'templateId': 'float', 'source': 'str', 'status': 'str', 'hasExpiredRecipients': 'str', 'folderId': 'str', 'orderByColumn': 'str', 'orderByDirection': 'str'},
          'param_defaults': {'orderByDirection': 'desc'},
          'param_docs': {'query': 'The search query.',
                         'page': 'The pagination page number, starts at 1.',
                         'perPage': 'The number of items per page.',
                         'type': 'Filter envelopes by type (DOCUMENT or TEMPLATE).',
                         'templateId': 'Filter envelopes by the template ID used to create it.',
                         'source': 'Filter envelopes by how it was created.',
                         'status': 'Filter envelopes by the current status.',
                         'hasExpiredRecipients': 'Filter for envelopes that have at least one recipient whose signing link has expired.',
                         'folderId': 'Filter envelopes by folder ID.',
                         'orderByDirection': 'Sort direction.'}},
         {'group': 'envelope',
          'name': 'envelope_audit_log_find',
          'path': '/envelope/{envelopeId}/audit-log',
          'verb': 'GET',
          'summary': 'Get envelope audit logs',
          'route_params': ['envelopeId'],
          'query_params': ['page', 'perPage', 'orderByColumn', 'orderByDirection'],
          'required_params': ['envelopeId'],
          'param_types': {'envelopeId': 'str', 'page': 'float', 'perPage': 'float', 'orderByColumn': 'str', 'orderByDirection': 'str'},
          'param_docs': {'envelopeId': 'Envelope ID', 'page': 'The pagination page number, starts at 1.', 'perPage': 'The number of items per page.'}},
         {'group': 'envelope',
          'name': 'envelope_audit_log_download_pdf',
          'path': '/envelope/{envelopeId}/audit-log/download',
          'verb': 'GET',
          'summary': 'Download envelope audit log PDF',
          'route_params': ['envelopeId'],
          'required_params': ['envelopeId'],
          'param_types': {'envelopeId': 'str'},
          'param_docs': {'envelopeId': 'The ID of the envelope to download the audit log for.'}},
         {'group': 'envelope',
          'name': 'envelope_certificate_download_pdf',
          'path': '/envelope/{envelopeId}/certificate/download',
          'verb': 'GET',
          'summary': 'Download envelope certificate PDF',
          'route_params': ['envelopeId'],
          'required_params': ['envelopeId'],
          'param_types': {'envelopeId': 'str'},
          'param_docs': {'envelopeId': 'The ID of the envelope to download the certificate for.'}},
         {'group': 'envelope', 'name': 'envelope_get', 'path': '/envelope/{envelopeId}', 'verb': 'GET', 'summary': 'Get envelope', 'route_params': ['envelopeId'], 'required_params': ['envelopeId'], 'param_types': {'envelopeId': 'str'}},
         {'group': 'envelope', 'name': 'envelope_get_many', 'path': '/envelope/get-many', 'verb': 'POST', 'summary': 'Get multiple envelopes', 'body_params': ['ids'], 'request_content_type': 'application/json', 'required_params': ['ids'], 'param_types': {'ids': 'dict'}},
         {'group': 'envelope', 'name': 'envelope_create', 'path': '/envelope/create', 'verb': 'POST', 'summary': 'Create envelope', 'body_params': ['payload', 'files'], 'file_params': ['files'], 'request_content_type': 'multipart/form-data', 'required_params': ['payload'], 'param_types': {'payload': 'dict', 'files': 'list'}},
         {'group': 'envelope', 'name': 'envelope_use', 'path': '/envelope/use', 'verb': 'POST', 'summary': 'Use envelope', 'body_params': ['payload', 'files'], 'file_params': ['files'], 'request_content_type': 'multipart/form-data', 'required_params': ['payload'], 'param_types': {'payload': 'dict', 'files': 'list'}},
         {'group': 'envelope', 'name': 'envelope_update', 'path': '/envelope/update', 'verb': 'POST', 'summary': 'Update envelope', 'body_params': ['envelopeId', 'data', 'meta'], 'request_content_type': 'application/json', 'required_params': ['envelopeId'], 'param_types': {'envelopeId': 'str', 'data': 'dict', 'meta': 'dict'}},
         {'group': 'envelope', 'name': 'envelope_delete', 'path': '/envelope/delete', 'verb': 'POST', 'summary': 'Delete envelope', 'body_params': ['envelopeId'], 'request_content_type': 'application/json', 'required_params': ['envelopeId'], 'param_types': {'envelopeId': 'str'}},
         {'group': 'envelope', 'name': 'envelope_cancel', 'path': '/envelope/cancel', 'verb': 'POST', 'summary': 'Cancel envelope', 'body_params': ['envelopeId', 'reason'], 'request_content_type': 'application/json', 'required_params': ['envelopeId'], 'param_types': {'envelopeId': 'str', 'reason': 'str'}},
         {'group': 'envelope',
          'name': 'envelope_duplicate',
          'path': '/envelope/duplicate',
          'verb': 'POST',
          'summary': 'Duplicate envelope',
          'body_params': ['envelopeId', 'includeRecipients', 'includeFields'],
          'request_content_type': 'application/json',
          'required_params': ['envelopeId'],
          'param_types': {'envelopeId': 'str', 'includeRecipients': 'bool', 'includeFields': 'bool'},
          'param_defaults': {'includeRecipients': True, 'includeFields': True}},
         {'group': 'envelope', 'name': 'envelope_distribute', 'path': '/envelope/distribute', 'verb': 'POST', 'summary': 'Distribute envelope', 'body_params': ['envelopeId', 'meta'], 'request_content_type': 'application/json', 'required_params': ['envelopeId'], 'param_types': {'envelopeId': 'str', 'meta': 'dict'}},
         {'group': 'envelope', 'name': 'envelope_redistribute', 'path': '/envelope/redistribute', 'verb': 'POST', 'summary': 'Redistribute envelope', 'body_params': ['envelopeId', 'recipients'], 'request_content_type': 'application/json', 'required_params': ['envelopeId', 'recipients'], 'param_types': {'envelopeId': 'str', 'recipients': 'list'}},
         {'group': 'document', 'name': 'document_get', 'path': '/document/{documentId}', 'verb': 'GET', 'summary': 'Get document', 'route_params': ['documentId'], 'required_params': ['documentId'], 'param_types': {'documentId': 'float'}, 'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_get_many',
          'path': '/document/get-many',
          'verb': 'POST',
          'summary': 'Get multiple documents',
          'body_params': ['documentIds'],
          'request_content_type': 'application/json',
          'required_params': ['documentIds'],
          'param_types': {'documentIds': 'list'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_find',
          'path': '/document',
          'verb': 'GET',
          'summary': 'Find documents',
          'query_params': ['query', 'page', 'perPage', 'templateId', 'source', 'status', 'hasExpiredRecipients', 'folderId', 'orderByColumn', 'orderByDirection'],
          'param_types': {'query': 'str', 'page': 'float', 'perPage': 'float', 'templateId': 'float', 'source': 'str', 'status': 'str', 'hasExpiredRecipients': 'str', 'folderId': 'str', 'orderByColumn': 'str', 'orderByDirection': 'str'},
          'param_defaults': {'orderByDirection': 'desc'},
          'param_docs': {'query': 'The search query.',
                         'page': 'The pagination page number, starts at 1.',
                         'perPage': 'The number of items per page.',
                         'templateId': 'Filter documents by the template ID used to create it.',
                         'source': 'Filter documents by how it was created.',
                         'status': 'Filter documents by the current status',
                         'hasExpiredRecipients': 'Filter for documents that have at least one recipient whose signing link has expired.',
                         'folderId': 'Filter documents by folder ID'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_create',
          'path': '/document/create',
          'verb': 'POST',
          'summary': 'Create document',
          'body_params': ['payload', 'file'],
          'file_params': ['file'],
          'request_content_type': 'multipart/form-data',
          'required_params': ['file', 'payload'],
          'param_types': {'payload': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_update',
          'path': '/document/update',
          'verb': 'POST',
          'summary': 'Update document',
          'body_params': ['documentId', 'data', 'meta'],
          'request_content_type': 'application/json',
          'required_params': ['documentId'],
          'param_types': {'documentId': 'float', 'data': 'dict', 'meta': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_delete',
          'path': '/document/delete',
          'verb': 'POST',
          'summary': 'Delete document',
          'body_params': ['documentId'],
          'request_content_type': 'application/json',
          'required_params': ['documentId'],
          'param_types': {'documentId': 'float'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_duplicate',
          'path': '/document/duplicate',
          'verb': 'POST',
          'summary': 'Duplicate document',
          'body_params': ['documentId'],
          'request_content_type': 'application/json',
          'required_params': ['documentId'],
          'param_types': {'documentId': 'float'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_distribute',
          'path': '/document/distribute',
          'verb': 'POST',
          'summary': 'Distribute document',
          'body_params': ['documentId', 'meta'],
          'request_content_type': 'application/json',
          'required_params': ['documentId'],
          'param_types': {'documentId': 'float', 'meta': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_redistribute',
          'path': '/document/redistribute',
          'verb': 'POST',
          'summary': 'Redistribute document',
          'body_params': ['documentId', 'recipients'],
          'request_content_type': 'application/json',
          'required_params': ['documentId', 'recipients'],
          'param_types': {'documentId': 'float', 'recipients': 'list'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_download',
          'path': '/document/{documentId}/download',
          'verb': 'GET',
          'summary': 'Download document',
          'route_params': ['documentId'],
          'query_params': ['version'],
          'required_params': ['documentId'],
          'param_types': {'documentId': 'float', 'version': 'str'},
          'param_defaults': {'version': 'signed'},
          'param_docs': {'documentId': 'The ID of the document to download.', 'version': 'The version of the document to download. "signed" returns the completed document with signatures, "original" returns the original uploaded document.'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_download_beta',
          'path': '/document/{documentId}/download-beta',
          'verb': 'GET',
          'summary': 'Download document (beta)',
          'route_params': ['documentId'],
          'query_params': ['version'],
          'required_params': ['documentId'],
          'param_types': {'documentId': 'float', 'version': 'str'},
          'param_defaults': {'version': 'signed'},
          'param_docs': {'documentId': 'The ID of the document to download.', 'version': 'The version of the document to download. "signed" returns the completed document with signatures, "original" returns the original uploaded document.'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_create_document_temporary',
          'path': '/document/create/beta',
          'verb': 'POST',
          'summary': 'Create document',
          'body_params': ['title', 'externalId', 'visibility', 'globalAccessAuth', 'globalActionAuth', 'formValues', 'folderId', 'recipients', 'attachments', 'meta'],
          'request_content_type': 'application/json',
          'required_params': ['title'],
          'param_types': {'title': 'str', 'externalId': 'str', 'visibility': 'str', 'globalAccessAuth': 'list', 'globalActionAuth': 'list', 'formValues': 'dict', 'folderId': 'str', 'recipients': 'list', 'attachments': 'list', 'meta': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_attachment_create',
          'path': '/document/attachment/create',
          'verb': 'POST',
          'summary': 'Create attachment',
          'body_params': ['documentId', 'data'],
          'request_content_type': 'application/json',
          'required_params': ['data', 'documentId'],
          'param_types': {'documentId': 'float', 'data': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_attachment_update',
          'path': '/document/attachment/update',
          'verb': 'POST',
          'summary': 'Update attachment',
          'body_params': ['id', 'data'],
          'request_content_type': 'application/json',
          'required_params': ['data', 'id'],
          'param_types': {'id': 'str', 'data': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'document_attachment_delete',
          'path': '/document/attachment/delete',
          'verb': 'POST',
          'summary': 'Delete attachment',
          'body_params': ['id'],
          'request_content_type': 'application/json',
          'required_params': ['id'],
          'param_types': {'id': 'str'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document', 'name': 'document_attachment_find', 'path': '/document/attachment', 'verb': 'GET', 'summary': 'Find attachments', 'query_params': ['documentId'], 'required_params': ['documentId'], 'param_types': {'documentId': 'float'}, 'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document', 'name': 'field_get_document_field', 'path': '/document/field/{fieldId}', 'verb': 'GET', 'summary': 'Get document field', 'route_params': ['fieldId'], 'required_params': ['fieldId'], 'param_types': {'fieldId': 'float'}, 'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'field_create_document_field',
          'path': '/document/field/create',
          'verb': 'POST',
          'summary': 'Create document field',
          'body_params': ['documentId', 'field'],
          'request_content_type': 'application/json',
          'required_params': ['documentId', 'field'],
          'param_types': {'documentId': 'float', 'field': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'field_create_document_fields',
          'path': '/document/field/create-many',
          'verb': 'POST',
          'summary': 'Create document fields',
          'body_params': ['documentId', 'fields'],
          'request_content_type': 'application/json',
          'required_params': ['documentId', 'fields'],
          'param_types': {'documentId': 'float', 'fields': 'list'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'field_update_document_field',
          'path': '/document/field/update',
          'verb': 'POST',
          'summary': 'Update document field',
          'body_params': ['documentId', 'field'],
          'request_content_type': 'application/json',
          'required_params': ['documentId', 'field'],
          'param_types': {'documentId': 'float', 'field': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'field_update_document_fields',
          'path': '/document/field/update-many',
          'verb': 'POST',
          'summary': 'Update document fields',
          'body_params': ['documentId', 'fields'],
          'request_content_type': 'application/json',
          'required_params': ['documentId', 'fields'],
          'param_types': {'documentId': 'float', 'fields': 'list'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'field_delete_document_field',
          'path': '/document/field/delete',
          'verb': 'POST',
          'summary': 'Delete document field',
          'body_params': ['fieldId'],
          'request_content_type': 'application/json',
          'required_params': ['fieldId'],
          'param_types': {'fieldId': 'float'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'field_create_template_field',
          'path': '/template/field/create',
          'verb': 'POST',
          'summary': 'Create template field',
          'body_params': ['templateId', 'field'],
          'request_content_type': 'application/json',
          'required_params': ['field', 'templateId'],
          'param_types': {'templateId': 'float', 'field': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template', 'name': 'field_get_template_field', 'path': '/template/field/{fieldId}', 'verb': 'GET', 'summary': 'Get template field', 'route_params': ['fieldId'], 'required_params': ['fieldId'], 'param_types': {'fieldId': 'float'}, 'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'field_create_template_fields',
          'path': '/template/field/create-many',
          'verb': 'POST',
          'summary': 'Create template fields',
          'body_params': ['templateId', 'fields'],
          'request_content_type': 'application/json',
          'required_params': ['fields', 'templateId'],
          'param_types': {'templateId': 'float', 'fields': 'list'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'field_update_template_field',
          'path': '/template/field/update',
          'verb': 'POST',
          'summary': 'Update template field',
          'body_params': ['templateId', 'field'],
          'request_content_type': 'application/json',
          'required_params': ['field', 'templateId'],
          'param_types': {'templateId': 'float', 'field': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'field_update_template_fields',
          'path': '/template/field/update-many',
          'verb': 'POST',
          'summary': 'Update template fields',
          'body_params': ['templateId', 'fields'],
          'request_content_type': 'application/json',
          'required_params': ['fields', 'templateId'],
          'param_types': {'templateId': 'float', 'fields': 'list'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'field_delete_template_field',
          'path': '/template/field/delete',
          'verb': 'POST',
          'summary': 'Delete template field',
          'body_params': ['fieldId'],
          'request_content_type': 'application/json',
          'required_params': ['fieldId'],
          'param_types': {'fieldId': 'float'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'folder',
          'name': 'folder_find_folders',
          'path': '/folder',
          'verb': 'GET',
          'summary': 'Find folders',
          'query_params': ['query', 'page', 'perPage', 'parentId', 'type'],
          'param_types': {'query': 'str', 'page': 'float', 'perPage': 'float', 'parentId': 'str', 'type': 'str'},
          'param_docs': {'query': 'The search query.', 'page': 'The pagination page number, starts at 1.', 'perPage': 'The number of items per page.'}},
         {'group': 'folder', 'name': 'folder_create_folder', 'path': '/folder/create', 'verb': 'POST', 'summary': 'Create new folder', 'body_params': ['name', 'parentId', 'type'], 'request_content_type': 'application/json', 'required_params': ['name'], 'param_types': {'name': 'str', 'parentId': 'str', 'type': 'str'}},
         {'group': 'folder', 'name': 'folder_update_folder', 'path': '/folder/update', 'verb': 'POST', 'summary': 'Update folder', 'body_params': ['folderId', 'data'], 'request_content_type': 'application/json', 'required_params': ['data', 'folderId'], 'param_types': {'folderId': 'str', 'data': 'dict'}},
         {'group': 'folder', 'name': 'folder_delete_folder', 'path': '/folder/delete', 'verb': 'POST', 'summary': 'Delete folder', 'body_params': ['folderId'], 'request_content_type': 'application/json', 'required_params': ['folderId'], 'param_types': {'folderId': 'str'}},
         {'group': 'document',
          'name': 'recipient_get_document_recipient',
          'path': '/document/recipient/{recipientId}',
          'verb': 'GET',
          'summary': 'Get document recipient',
          'route_params': ['recipientId'],
          'required_params': ['recipientId'],
          'param_types': {'recipientId': 'float'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'recipient_create_document_recipient',
          'path': '/document/recipient/create',
          'verb': 'POST',
          'summary': 'Create document recipient',
          'body_params': ['documentId', 'recipient'],
          'request_content_type': 'application/json',
          'required_params': ['documentId', 'recipient'],
          'param_types': {'documentId': 'float', 'recipient': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'recipient_create_document_recipients',
          'path': '/document/recipient/create-many',
          'verb': 'POST',
          'summary': 'Create document recipients',
          'body_params': ['documentId', 'recipients'],
          'request_content_type': 'application/json',
          'required_params': ['documentId', 'recipients'],
          'param_types': {'documentId': 'float', 'recipients': 'list'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'recipient_update_document_recipient',
          'path': '/document/recipient/update',
          'verb': 'POST',
          'summary': 'Update document recipient',
          'body_params': ['documentId', 'recipient'],
          'request_content_type': 'application/json',
          'required_params': ['documentId', 'recipient'],
          'param_types': {'documentId': 'float', 'recipient': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'recipient_update_document_recipients',
          'path': '/document/recipient/update-many',
          'verb': 'POST',
          'summary': 'Update document recipients',
          'body_params': ['documentId', 'recipients'],
          'request_content_type': 'application/json',
          'required_params': ['documentId', 'recipients'],
          'param_types': {'documentId': 'float', 'recipients': 'list'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'document',
          'name': 'recipient_delete_document_recipient',
          'path': '/document/recipient/delete',
          'verb': 'POST',
          'summary': 'Delete document recipient',
          'body_params': ['recipientId'],
          'request_content_type': 'application/json',
          'required_params': ['recipientId'],
          'param_types': {'recipientId': 'float'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'recipient_get_template_recipient',
          'path': '/template/recipient/{recipientId}',
          'verb': 'GET',
          'summary': 'Get template recipient',
          'route_params': ['recipientId'],
          'required_params': ['recipientId'],
          'param_types': {'recipientId': 'float'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'recipient_create_template_recipient',
          'path': '/template/recipient/create',
          'verb': 'POST',
          'summary': 'Create template recipient',
          'body_params': ['templateId', 'recipient'],
          'request_content_type': 'application/json',
          'required_params': ['recipient', 'templateId'],
          'param_types': {'templateId': 'float', 'recipient': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'recipient_create_template_recipients',
          'path': '/template/recipient/create-many',
          'verb': 'POST',
          'summary': 'Create template recipients',
          'body_params': ['templateId', 'recipients'],
          'request_content_type': 'application/json',
          'required_params': ['recipients', 'templateId'],
          'param_types': {'templateId': 'float', 'recipients': 'list'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'recipient_update_template_recipient',
          'path': '/template/recipient/update',
          'verb': 'POST',
          'summary': 'Update template recipient',
          'body_params': ['templateId', 'recipient'],
          'request_content_type': 'application/json',
          'required_params': ['recipient', 'templateId'],
          'param_types': {'templateId': 'float', 'recipient': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'recipient_update_template_recipients',
          'path': '/template/recipient/update-many',
          'verb': 'POST',
          'summary': 'Update template recipients',
          'body_params': ['templateId', 'recipients'],
          'request_content_type': 'application/json',
          'required_params': ['recipients', 'templateId'],
          'param_types': {'templateId': 'float', 'recipients': 'list'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'recipient_delete_template_recipient',
          'path': '/template/recipient/delete',
          'verb': 'POST',
          'summary': 'Delete template recipient',
          'body_params': ['recipientId'],
          'request_content_type': 'application/json',
          'required_params': ['recipientId'],
          'param_types': {'recipientId': 'float'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'template_find_templates',
          'path': '/template',
          'verb': 'GET',
          'summary': 'Find templates',
          'query_params': ['query', 'page', 'perPage', 'type', 'folderId'],
          'param_types': {'query': 'str', 'page': 'float', 'perPage': 'float', 'type': 'str', 'folderId': 'str'},
          'param_docs': {'query': 'The search query.', 'page': 'The pagination page number, starts at 1.', 'perPage': 'The number of items per page.', 'type': 'Filter templates by type.', 'folderId': 'The ID of the folder to filter templates by.'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template', 'name': 'template_get_template_by_id', 'path': '/template/{templateId}', 'verb': 'GET', 'summary': 'Get template', 'route_params': ['templateId'], 'required_params': ['templateId'], 'param_types': {'templateId': 'float'}, 'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'template_get_many',
          'path': '/template/get-many',
          'verb': 'POST',
          'summary': 'Get multiple templates',
          'body_params': ['templateIds'],
          'request_content_type': 'application/json',
          'required_params': ['templateIds'],
          'param_types': {'templateIds': 'list'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'template_create_template',
          'path': '/template/create',
          'verb': 'POST',
          'summary': 'Create template',
          'body_params': ['payload', 'file'],
          'file_params': ['file'],
          'request_content_type': 'multipart/form-data',
          'required_params': ['file', 'payload'],
          'param_types': {'payload': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'template_create_template_temporary',
          'path': '/template/create/beta',
          'verb': 'POST',
          'summary': 'Create template',
          'body_params': ['title', 'folderId', 'externalId', 'visibility', 'globalAccessAuth', 'globalActionAuth', 'publicTitle', 'publicDescription', 'type', 'meta', 'attachments'],
          'request_content_type': 'application/json',
          'required_params': ['title'],
          'param_types': {'title': 'str', 'folderId': 'str', 'externalId': 'str', 'visibility': 'str', 'globalAccessAuth': 'list', 'globalActionAuth': 'list', 'publicTitle': 'str', 'publicDescription': 'str', 'type': 'str', 'meta': 'dict', 'attachments': 'list'},
          'param_defaults': {'globalAccessAuth': [], 'globalActionAuth': []},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'template_update_template',
          'path': '/template/update',
          'verb': 'POST',
          'summary': 'Update template',
          'body_params': ['templateId', 'data', 'meta'],
          'request_content_type': 'application/json',
          'required_params': ['templateId'],
          'param_types': {'templateId': 'float', 'data': 'dict', 'meta': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'template_duplicate_template',
          'path': '/template/duplicate',
          'verb': 'POST',
          'summary': 'Duplicate template',
          'body_params': ['templateId'],
          'request_content_type': 'application/json',
          'required_params': ['templateId'],
          'param_types': {'templateId': 'float'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'template_delete_template',
          'path': '/template/delete',
          'verb': 'POST',
          'summary': 'Delete template',
          'body_params': ['templateId'],
          'request_content_type': 'application/json',
          'required_params': ['templateId'],
          'param_types': {'templateId': 'float'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'template_create_document_from_template',
          'path': '/template/use',
          'verb': 'POST',
          'summary': 'Use template',
          'body_params': ['templateId', 'externalId', 'recipients', 'distributeDocument', 'customDocumentDataId', 'customDocumentData', 'folderId', 'prefillFields', 'override', 'attachments', 'formValues'],
          'request_content_type': 'application/json',
          'required_params': ['recipients', 'templateId'],
          'param_types': {'templateId': 'float', 'externalId': 'str', 'recipients': 'list', 'distributeDocument': 'bool', 'customDocumentDataId': 'str', 'customDocumentData': 'list', 'folderId': 'str', 'prefillFields': 'list', 'override': 'dict', 'attachments': 'list', 'formValues': 'dict'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'template_create_template_direct_link',
          'path': '/template/direct/create',
          'verb': 'POST',
          'summary': 'Create direct link',
          'body_params': ['templateId', 'directRecipientId'],
          'request_content_type': 'application/json',
          'required_params': ['templateId'],
          'param_types': {'templateId': 'float', 'directRecipientId': 'float'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'template_delete_template_direct_link',
          'path': '/template/direct/delete',
          'verb': 'POST',
          'summary': 'Delete direct link',
          'body_params': ['templateId'],
          'request_content_type': 'application/json',
          'required_params': ['templateId'],
          'param_types': {'templateId': 'float'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'template',
          'name': 'template_toggle_template_direct_link',
          'path': '/template/direct/toggle',
          'verb': 'POST',
          'summary': 'Toggle direct link',
          'body_params': ['templateId', 'enabled'],
          'request_content_type': 'application/json',
          'required_params': ['enabled', 'templateId'],
          'param_types': {'templateId': 'float', 'enabled': 'bool'},
          'docs_url': 'https://docs.documenso.com/docs/developers/api/migrate-to-envelopes'},
         {'group': 'embedding',
          'name': 'embedding_presign_create_embedding_presign_token',
          'path': '/embedding/create-presign-token',
          'verb': 'POST',
          'summary': 'Create embedding presign token',
          'body_params': ['expiresIn', 'scope'],
          'request_content_type': 'application/json',
          'param_types': {'expiresIn': 'float', 'scope': 'str'},
          'param_defaults': {'expiresIn': 60}},
         {'group': 'embedding', 'name': 'embedding_presign_verify_embedding_presign_token', 'path': '/embedding/verify-presign-token', 'verb': 'POST', 'summary': 'Verify embedding presign token', 'body_params': ['token', 'scope'], 'request_content_type': 'application/json', 'required_params': ['token'], 'param_types': {'token': 'str', 'scope': 'str'}}]}
