"""Async Documenso v2 API client built on fastspec

Create a client with `documenso_client()` and call generated operations:
`await cli.envelope.envelope_create(...)`, `await cli.document.document_get(...)`, etc.

## Updating the spec

`_spec.py` is a snapshot of the Documenso OpenAPI spec. Regenerate it with the `fastdocumenso_update` command when the API changes.

Documenso's OpenAPI spec marks file-upload parameters with an empty item schema (`{}`) instead of the standard `{'type': 'string', 'format': 'binary'}`, so `SpecParser.from_openapi` doesn't detect them as file params. Without that detection, `files` is treated as an ordinary JSON field — and passing a real file object then fails, because `httpx`/`json.dumps` can't serialize a file object.

Docs: https://AnswerDotAI.github.io/fastdocumenso/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['SPEC_URL', 'documenso_client', 'update_spec']

# %% ../nbs/00_core.ipynb #b0d129e4
import os, json, httpx
from dataclasses import replace
from fastcore.utils import *
from fastcore.script import call_parse
from fastspec.spec import SpecParser
from fastspec.oapi import OpenAPIClient
from nbdev.config import get_config

from ._spec import spec as _spec

# %% ../nbs/00_core.ipynb #c5b30ee7
def _encode_form(d):
    "Documenso multipart endpoints expect dict/list parts (e.g. `payload`) as JSON strings"
    return {k: json.dumps(v) if isinstance(v,(dict,list)) else v for k,v in d.items()}

# %% ../nbs/00_core.ipynb #5c920601
def documenso_client(
    api_key:str|None=None,  # Documenso API token; defaults to $DOCUMENSO_API_KEY
    base_url:str|None=None, # defaults to $DOCUMENSO_API_URL or the documenso.com cloud
)->OpenAPIClient:           # groups as attributes, ops as awaitable methods
    "Async Documenso v2 API client"
    spec = SpecParser.from_dict(_spec)
    spec.base_url = base_url or os.environ.get('DOCUMENSO_API_URL', spec.base_url)
    return OpenAPIClient(spec, headers={'Authorization': api_key or os.environ['DOCUMENSO_API_KEY']}, form_encoder=_encode_form)

# %% ../nbs/00_core.ipynb #24433961
SPEC_URL = 'https://app.documenso.com/api/v2/openapi.json'

# %% ../nbs/00_core.ipynb #92ffb995
# Documenso's spec uses empty item schemas for file uploads (not the standard `format: binary`)
_FILE_OPS = {'envelope_item_create_many': 'files', 'envelope_create': 'files', 'envelope_use': 'files',
             'document_create': 'file', 'template_create_template': 'file'}

# %% ../nbs/00_core.ipynb #461ce9a2
@call_parse
def update_spec(
    url:str=SPEC_URL, # OpenAPI spec URL to fetch
    out:str=None, # Output path; defaults to `_spec.py` in the package
):
    "Regenerate `_spec.py` from the Documenso OpenAPI spec"
    out = Path(out) if out else get_config().lib_path/'_spec.py'
    raw = httpx.get(url, follow_redirects=True).raise_for_status().json()
    parser = SpecParser.from_openapi(dict2obj(raw))
    parser.ops = [replace(o, file_params=[_FILE_OPS[o.name]]) if o.name in _FILE_OPS else o for o in parser.ops]
    parser.save(out)
    return f"Saved {len(parser.ops)} ops to {out}"
